---
name: CI
on:
  push: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "/home/runner/.cache/bazel"
          key: bazel
      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
      - name: Build
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" build //...
      - name: Test
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" test //...
          "${GITHUB_WORKSPACE}/bin/bazel" coverage ... --test_arg=covermode=count
      - name: Get Test Output
        id: test_dir
        run: |
          echo "::set-output name=bazel_test_dir::$(${GITHUB_WORKSPACE}/bin/bazel info bazel-testlogs)"
      - name: Goveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: ${{ steps.test_dir.outputs.bazel_test_dir }}/epiweek_test/coverage.dat
      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ${{ steps.test_dir.outputs.bazel_test_dir }}/epiweek_test/coverage.dat
          verbose: true
